// Auto Generated by North Sky
// You may modify this file if the format is not changed.

page[0]="/links.html"; count[0]=1151;
page[1]="/graph.html"; count[1]=1520;
page[2]="/hist.html"; count[2]=2160;
page[3]="/paper.html"; count[3]=2509;
page[4]="/code.html"; count[4]=1457;
page[5]="/tabs.html"; count[5]=1263;
page[6]="/ident.html"; count[6]=2407;
page[7]="/defs.html"; count[7]=1473;
page[8]="/main.html"; count[8]=7058;
